FROM yarnpkg/node-yarn as build-stage
WORKDIR /app
COPY package.json /app/
RUN yarn
COPY ./ /app/
RUN yarn build

FROM nginx:1.15
COPY --from=build-stage /app/build/ /usr/share/nginx/html
# Copy the default nginx.conf provided by tiangolo/node-frontend
COPY --from=build-stage /nginx.conf /etc/nginx/conf.d/default.conf
