version: '3'
services:
  server:
    container_name: utl-server
    build:
        context: ./server
    environment:
      DB_PORT: 3306
    ports:
     - "3001:3001"
    links:
      - mysql
    restart: always
    volumes:
      - ./server:/server
      - /server/node_modules
    command: nodemon /server/index.js

  client:
    container_name: utl-client
    build:
        context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    command: npm start

  phpmyadmin:
    container_name: utl-phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'

  mysql:
    container_name: utl-mysql
    image: mysql:5.7.24
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
      MYSQL_DATABASE: utl
    restart: always

volumes:
  db_data:
