version: '2'
services:
  mysql:
    container_name: utl-mysql
    image: mysql:5.7.24
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
      MYSQL_DATABASE: utl
    restart: always
  server:
    container_name: utl-server
    build:
        context: ./server
    environment:
      DB: utl
      DB_USER: user
      DB_PWD: pwd
      DB_HOST: mysql
    ports:
     - "3001:3001"
    links:
      - mysql
    restart: always
    command: nodemon /server/index.js

  client:
    container_name: utl-client
    build:
        context: ./client
        dockerfile: Dockerfile-build
    ports:
      - "3000:3000"
    command: npm start

volumes:
  db_data:
