FROM node:10.14.2-jessie

ENV NODE_ENV=development

ADD client/package.json /client/package.json
ADD server/package.json /server/package.json

RUN cd /client && yarn && yarn build
RUN cd /server && yarn

ENV NODE_PATH=/client/node_modules
ENV PATH=$PATH:/client/node_modules/.bin:/server/node_modules/.bin
COPY . /client
COPY . /server

EXPOSE 3000
EXPOSE 35729

CMD yarn start:dev
