const ADJECTIVES = [
  { type: 'suffix', value: 'ancien' },
  { type: 'prefix', value: 'beau' },
  { type: 'suffix', value: 'bon' },
  { type: 'suffix', value: 'en bonne santé' },
  { type: 'suffix', value: 'calme' },
  { type: 'suffix', value: 'chanceux' },
  { type: 'suffix', value: 'chaud' },
  { type: 'suffix', value: 'confiant' },
  { type: 'prefix', value: 'dernier' },
  { type: 'suffix', value: 'different' },
  { type: 'suffix', value: 'doux' },
  { type: 'suffix', value: 'dynamique' },
  { type: 'suffix', value: 'dégouté' },
  { type: 'suffix', value: 'déprimé' },
  { type: 'suffix', value: 'ennuyé' },
  { type: 'suffix', value: 'enthousiaste' },
  { type: 'suffix', value: 'flou' },
  { type: 'suffix', value: 'fort' },
  { type: 'suffix', value: 'frais' },
  { type: 'suffix', value: 'froid' },
  { type: 'suffix', value: 'gentil' },
  { type: 'prefix', value: 'grand' },
  { type: 'suffix', value: 'gros' },
  { type: 'suffix', value: 'heureux' },
  { type: 'suffix', value: 'inquiet' },
  { type: 'suffix', value: 'investi' },
  { type: 'suffix', value: 'jeune' },
  { type: 'suffix', value: 'joueur' },
  { type: 'prefix', value: 'large' },
  { type: 'suffix', value: 'long' },
  { type: 'suffix', value: 'malade' },
  { type: 'suffix', value: 'mauvais' },
  { type: 'suffix', value: 'mince' },
  { type: 'suffix', value: 'net' },
  { type: 'suffix', value: 'nouveau' },
  { type: 'prefix', value: 'petit' },
  { type: 'suffix', value: 'premier' },
  { type: 'suffix', value: 'ravi' },
  { type: 'suffix', value: 'rempli' },
  { type: 'suffix', value: 'serein' },
  { type: 'suffix', value: 'surpris' },
  { type: 'suffix', value: 'triste' },
  { type: 'suffix', value: 'vide' },
  { type: 'suffix', value: 'énergique' },
  { type: 'suffix', value: 'énervé' },
];

const NOUNS = [
  'aigle',
  'canard',
  'cheval',
  'chien',
  'cochon',
  'criquet',
  'dauphin',
  'escargot',
  'faucon',
  'gorille',
  'hibou',
  'lapin',
  'lion',
  'loup',
  'lézard',
  'moustique',
  'mouton',
  'oiseau',
  'ours',
  'papillon',
  'perroquet',
  'phoque',
  'pingouin',
  'poisson',
  'renard',
  'requin',
  'serpent',
  'singe',
  'taureau',
  'âne',
  'écureuil',
  'éléphant',
];

export default () => {
  const adjective = ADJECTIVES[Math.floor(Math.random() * ADJECTIVES.length)];
  const noun = NOUNS[Math.floor(Math.random() * NOUNS.length)];
  const randomName = (adjective.type === 'prefix'
    ? `${adjective.value}-${noun}`
    : `${noun}-${adjective.value}`);
  return Array.from(randomName).map((letter, i) => (i === 0 ? letter.toUpperCase() : letter)).join('').replace(/ /g, '-');
};
