const PLAYER_STATUS = {
  LOBBY: 'LOBBY',
  WAITING_CHANNEL: 'WAITING_CHANNEL',
};

const CHANNEL_STATUS = {
  GAMING: 'GAMING',
  WAITING_GAME: 'WAITING_GAME',
};

module.exports = { PLAYER_STATUS, CHANNEL_STATUS };
