const PLAYER_STATUS = {
  LOBBY: 'LOBBY',
  WAITING_CHANNEL: 'WAITING_CHANNEL',
};

const CHANNEL_STATUS = {
  IDLE: 'IDLE',
  WAITING_GAME: 'WAITING_GAME',
  PLAYING_CARD: 'PLAYING_CARD',
  JUDGING_CARD: 'JUDGING_CARD',
};

module.exports = { PLAYER_STATUS, CHANNEL_STATUS };
