INSERT INTO `Answers` (`id`, `text`) VALUES
(1, 'Ma bite'),
(2, 'Coller la Petite'),
(3, 'Les Chinois'),
(4, 'Les Noirs'),
(5, 'Soixante-dix vierges'),
(6, 'Un Juif, un unijambiste et un Belge'),
(7, 'Les Juifs'),
(8, 'Joseph Goebbels'),
(9, 'Me follow-back quand je l\'ai follow'),
(10, 'Des nudes de Michel Cymès'),
(11, 'La chatte à ta mère'),
(12, 'Me sucer'),
(13, 'La probité des Balkany'),
(14, 'Regarder un bon porno'),
(15, 'Un bras d\'enfant'),
(16, 'Un enfant Rohingya'),
(17, 'Logan Paul'),
(18, 'Le glyphosate'),
(19, 'Un charter rempli de Moldaves'),
(20, 'Un seigneur noir des Siths'),
(21, 'Ma bite et mon couteau'),
(22, 'Déféquer dans un melon'),
(23, 'Prendre un enfant par la main'),
(24, 'Filmer un cadavre pour faire le buzz'),
(25, 'La zoophilie'),
(26, 'L\'eau de Javel'),
(27, 'Un petit mojito sur les quais'),
(28, 'Du quinoa'),
(29, 'Une pipe vite fait entre deux avions'),
(30, 'La soupe populaire'),
(31, 'Un cubi de Villageoise'),
(32, 'Du surimi'),
(33, 'Regarder ses voisins avec des jumelles'),
(34, 'Sentir sa main après s\'être gratté les couilles'),
(35, 'La nation Française'),
(36, 'L\'affaire Fillon : la comédie musicale'),
(37, 'Sucer un pote pour lui rendre service'),
(38, 'Les soi-disant victimes d’Harvey Weinstein'),
(39, 'Avoir une érection pendant un entretien d’embauche'),
(40, 'La gaule matinale'),
(41, 'Une coupe menstruelle pleine'),
(42, 'La société de consommation'),
(43, 'Goûter son sperme juste pour voir'),
(44, 'Le dernier porno de Dorothée'),
(45, 'Michel Fourniret'),
(46, 'Eva Mendès'),
(47, 'La neutralité du Web'),
(48, 'La diarrhée post-concert de jazz manouche'),
(49, 'Du Smecta'),
(50, 'Une petite virée improvisée à Deauville'),
(51, 'Mohamed dans la soute de l’avion'),
(52, 'La fête de l’Huma’'),
(53, 'Un mode de vie altermondialiste'),
(54, 'L’école Montessori'),
(55, 'Charles Manson'),
(56, 'L\'odeur d\'un cadavre en décomposition'),
(57, 'Un AVC à 20 ans à cause de la cigarette'),
(58, 'La pilule de troisième génération'),
(59, 'Une prof en mini-jupe peu farouche'),
(60, 'Bryan dans la cuisine'),
(61, 'Le troisième bras de Jamel'),
(62, 'Laurent Delahousse'),
(63, 'Des sucettes à l’amiante'),
(64, 'Les enfants surdoués'),
(65, 'Sortir un album de rock chrétien'),
(66, 'Mettre du Patrick Sébastien à fond dans le bus'),
(67, 'Demander au DJ de mettre du Jul'),
(68, 'Mohamed et Toufik'),
(69, 'Le Bataclan un soir de Novembre'),
(70, 'Une rave party dans un hôpital désaffecté'),
(71, 'Marcher sur une seringue en sortant de Gare du Nord'),
(72, 'Une jambe de bois'),
(73, 'Un espèce d’oiseau bizarre'),
(74, 'Une petite giclée entre les deux yeux'),
(75, 'L’épilation du sillon inter fessier'),
(76, 'Le ticket de métro'),
(77, 'Emmanuel Macron'),
(78, 'Brogitte Macron'),
(79, 'Les Macron'),
(80, 'Une bûche de Noël'),
(81, 'Europe-Écologie-Les Verts'),
(82, 'François Bayrou'),
(83, 'La tente d’un sans-abri'),
(84, 'Une femme sexy avec un strabisme'),
(85, 'La go qui connaît pas Charo'),
(86, 'Baiser sa cousine'),
(87, 'Les bourgeois'),
(88, 'Les Somaliens'),
(89, 'Un autodafé'),
(90, 'Une épuration ethnique'),
(91, 'Loana'),
(92, 'Un lépreux sans chevilles'),
(93, 'Secouer un épileptique pendant un clip de Skrillex'),
(94, 'Les filles de 8 ans qui mettent des push-up'),
(95, 'Les mecs qui s’appellent Kévin'),
(96, 'Manger ses ongles de pied'),
(97, 'Les dimanches à Bamako'),
(98, 'Les antisémites'),
(99, 'Prendre une giclée de sperme'),
(100, 'Dormir avec sa petite sœur'),
(101, 'Bander sur le nouveau mec de sa sœur'),
(102, 'Des homosexuels sur un bûcher'),
(103, 'Brûler les femmes pour l’avenir de l’Humanité'),
(104, 'Marion Séclin'),
(105, 'Adolf Hitler'),
(106, 'De la crème de marrons bio'),
(107, 'Un steak de quinoa'),
(108, 'Le Roundup'),
(109, 'Le Parti Chrétien Démocrate'),
(110, 'Judas'),
(111, 'Les provinciaux'),
(112, 'Les bouseux dans leurs étables'),
(113, 'François Ier'),
(114, 'Cyril Hanouna'),
(115, 'Vincent Lagaf’'),
(116, 'La pouffiasse qui présente la Météo sur TF1'),
(117, 'BFM Business'),
(118, 'La Confédération Helvétique'),
(119, 'La Mecque'),
(120, 'Le cadavre de Johnny'),
(121, 'Ta mère'),
(122, 'Lionel Jospin'),
(123, 'Petit frère qui veut grandir trop vite'),
(124, 'Les asexuels'),
(125, 'La secte des LGBT'),
(126, 'Démonter un enfant trop gentil'),
(127, 'Monseigneur André XXIII'),
(128, 'Lady Diana'),
(129, 'Robert Pattinson'),
(130, 'Le miracle de la Shoah'),
(131, 'Un aspirateur Dyson'),
(132, 'Une chocogrenouille'),
(133, 'Lord Voldemort'),
(134, 'Une soirée belotte avec Alain Jupé'),
(135, 'Donner aux associations bienpensantes'),
(136, 'Le VIH'),
(137, 'Un cancer du cul'),
(138, 'Le cancer des ovaires généralisé'),
(139, 'Une poutre dans l’anus'),
(140, 'Boire trop de jus d’orange'),
(141, 'Mr. Poopy Butthole (Monsieur Boîte à Caca)'),
(142, 'Du beurre de cacahuète avec des morceaux'),
(143, 'Les brocolis'),
(144, 'La lettre "K"'),
(145, 'Sentir du gland même après la douche'),
(146, 'Brenda et Jason, parents à 13 ans'),
(147, 'Les gitans'),
(148, 'Les romanichels'),
(149, 'Acheter sa première caravane'),
(150, 'Faire du 95E à 11 ans'),
(151, 'Un enfant pottelé'),
(152, 'Faire son coming-out en Arabie Saoudite'),
(153, 'L’Algérie Française'),
(154, 'Les SS'),
(155, 'Patrick Swayze'),
(156, 'La CFDT'),
(157, 'Avoir les dents du fond qui baignent'),
(158, 'Sentir avant de rentrer'),
(159, 'Le PSG'),
(160, 'Le Qatar'),
(161, 'Le président Robert Mugabe'),
(162, 'Découper un enfant après lui avoir promis une PS4'),
(163, 'Les gens qui sentent le déo de supermarché'),
(164, 'Faire ses courses à Lidl'),
(165, 'Renverser les femmes voilées qui traversent le passage piétons'),
(166, 'La République en Marche'),
(167, 'Marine Le Pen'),
(168, 'Marc Olivier Fogiel'),
(169, 'La meuf de Squeezie'),
(170, 'Les Khmers rouges'),
(171, 'Le Saint Esprit'),
(172, 'Les abrutis de Marseillais'),
(173, 'L’aide humanitaire pour le Soudan'),
(174, 'La ville de Sedan'),
(175, 'Médecins Sans Frontières'),
(176, 'Regarder sa petite sœur sous la douche'),
(177, 'Renifler la culotte sale de sa mamie'),
(178, 'Le quinquennat d’Emmanuel Macron'),
(179, 'Le calendrier coquin d’Éric Zemmour'),
(180, 'Henry de Lesquen'),
(181, 'Le sang froid de Mélenchon'),
(182, 'La maladie de Lime'),
(183, 'Gilles de la Tourette'),
(184, 'Une cougar qui chante « Yakalelo »'),
(185, 'Se laver le pénis à l’eau bénite'),
(186, 'Faire l’amour en écoutant « Rire & Chansons »'),
(187, 'Un sketch de Didier Bénureau'),
(188, 'L’émasculateur du Mékong'),
(189, 'Le nain chauve dans Dragon Ball'),
(190, 'Un clafouti au foutre'),
(191, 'Une poêlée automnale girolles/mycoses'),
(192, 'Fourrer Mélania Trump'),
(193, 'Frank Michael'),
(194, 'Faire une balafre à son enfant pour qu’il ressemble à Anakin Skywalker'),
(195, 'Les pédés'),
(196, 'Une fanfiction érotique de Toadette avec Sasuke Uchiwa'),
(197, 'La bite à David Pujadas'),
(198, 'Le Syndicat National des Journalistes'),
(199, 'Le Syndicat des Eaux de Nogent le Roi'),
(200, 'La ville de Maubeuge'),
(201, 'La ville de Vierzon'),
(202, 'Rouler en « 406 Break »'),
(203, 'Un patrimoine génétique douteux'),
(204, 'Les corons'),
(205, 'Une orgie de Luthériens sur l’Autoroute A10'),
(206, 'Faire un go-fast pour acheter une bétonnière'),
(207, 'Être Portugaise, s’appeler Kelly et avoir été conçue dans une Renault Laguna'),
(208, 'La chicha en bas des blocs à Evry'),
(209, 'Vladimir Poutine torse nu qui chevauche un grizzli'),
(210, 'Le maréchal Pétain'),
(211, 'Katsuni'),
(212, 'Se faire sucer par un âne myopathe'),
(213, 'Omar Bongo'),
(214, 'La démocratie'),
(215, 'Un filet de sole meunière'),
(216, 'Nicolas Anelka'),
(217, 'Patrice Evra'),
(218, 'Annie Cordy'),
(219, 'Marc Dutroux'),
(220, 'Émile Louis'),
(221, 'L’inspecteur Derrick'),
(222, 'La tortue ninja qui bouffe des pizzas'),
(223, 'Pierre Ménès'),
(224, 'La transfert de Neymar au PSG'),
(225, 'Une poignée de porte'),
(226, 'Martine Aubry'),
(227, 'Une selle de vélo'),
(228, 'Une clé à molette'),
(229, 'Un sandwich au caca'),
(230, 'Légiférer sur le droit de tuer les roux'),
(231, 'Un débat parlementaire sur l’opportunité d’intervenir dans le conflit Syrien'),
(232, 'Un crumble de menstruations'),
(233, 'Détruire ton vagin avec un berlingot de lait'),
(234, 'Les quenouilles importées d’Italie'),
(235, 'Jean Marie Le Pen Gaming'),
(236, 'Alain Soral'),
(237, 'L’ASMR pour myopathes aveugles'),
(238, 'Jeremstar'),
(239, 'Les seins de Natoo'),
(240, 'Enjoy Phoenix en surpoids'),
(241, 'Faire une faciale à Mimie Mathy'),
(242, 'Le Power Ranger rose'),
(243, 'Sacha de "Pokémon"'),
(244, 'Sucer n’est pas tromper'),
(245, 'Être hétéro'),
(246, 'Jouer à FIFA le soir de Noël'),
(247, 'S’en griller une avant de baiser Titouan, le fils de la voisine'),
(248, 'Acheter une tablette Toshiba'),
(249, 'Se regarder dans le miroir après avoir massacré un labrador'),
(250, 'Culbuter le chien de la famille'),
(251, 'Être puceau et avoir des MST'),
(252, 'Sucer sa sœur en doigtant son frère'),
(253, 'Les gens accros à BFM'),
(254, 'Sucer un Bee Gees'),
(255, 'Gad Elmaleh'),
(256, 'Ouvrir un Skyblog en 2018'),
(257, 'Malika Le Pen'),
(258, 'Le revenu universel d\'existence'),
(259, 'League of Legends'),
(260, 'Benoît Hamon'),
(261, 'Jean Pierre Elkabbach'),
(262, 'François Asselineau'),
(263, 'Les banquiers et les assureurs'),
(264, 'Abdelkader, 76 ans, polygame'),
(265, 'Forrto'),
(266, 'Boubacar'),
(267, 'La dame-pipi'),
(268, 'Jean-Eudes'),
(269, 'Conchita la femme de ménage'),
(270, 'Ecouter Serge Lama sur Spotify'),
(271, 'Guy Carlier'),
(272, 'Tibo Inshape'),
(273, 'Les scientologues'),
(274, 'Les Mormons'),
(275, 'Les francs-maçons'),
(276, 'Un témoin de Jéhovah'),
(277, 'Un mâle-hétéro-blanc-cisgenre'),
(278, 'Une boucherie halal à Neuilly'),
(279, 'Une féministe racisée'),
(280, 'La barmitsva de Kader'),
(281, 'Edinson Cavani'),
(282, 'Un.e LGBTQIAPK'),
(283, 'Stigmatiser les mangeurs de porc'),
(284, 'Le racisme anti-blancs'),
(285, 'Les auvergnats'),
(286, 'Manuel Valls'),
(287, 'La communauté de l’Anneau'),
(288, 'Gandalf'),
(289, 'Une prostituée en alternance'),
(290, 'Une pute'),
(291, 'lorgan17'),
(292, 'Tuner un Fiat Multipla'),
(293, 'Des pièces pour le parcmètre'),
(294, 'Des Amish'),
(295, 'Le cousin de Christine Boutin'),
(296, 'Des coups de bite'),
(297, 'La ville de Rambouillet'),
(298, 'La SNCF'),
(299, 'Des pédophiles sur le Darknet'),
(300, 'Des enfants lépreux'),
(301, 'Des tongs avec des chaussettes'),
(302, 'Des survivalistes'),
(303, 'Des câbles HDMI'),
(304, 'Du ris de veau'),
(305, 'Faire les courses à Valenciennes'),
(306, 'Du beurre Poitou Charentes AOP'),
(307, 'Des jeunes filles d’Europe de l’Est'),
(308, 'La maîtresse du Président'),
(309, 'L’humour de Laurent Ruquier'),
(310, 'Donald Trump'),
(311, 'Michele Obama'),
(312, 'La treizième femme de Mamadou'),
(313, 'Un Targaryen'),
(314, 'Des femmes en niqab'),
(315, 'Des glaires pas frais'),
(316, 'Du sexe anal pendant la diarrhée'),
(317, 'Du sirop pour la toux'),
(318, 'Des poils roux'),
(319, 'Des cendres de juifs'),
(320, 'Refuser de cacher des juifs'),
(321, 'La triple péné'),
(322, 'Deux jeunes filles qui sont encore vierges'),
(323, 'Être puceau après 11 ans 2018'),
(324, 'Être juif et travailler dans l’audiovisuel'),
(325, 'Des animistes qui prient des cailloux'),
(326, 'Du poppers'),
(327, 'Du foutre plein les oreilles'),
(328, 'Judge Dredd'),
(329, 'Sœur Thérèse.com'),
(330, 'Maître Yoda'),
(331, 'Regarder TF1 en replay'),
(332, 'Enora Malagré'),
(333, 'Le Troisième Reich'),
(334, 'Eric Cartman'),
(335, 'Avoir une ossature lourde'),
(336, 'Les racines chrétiennes de la France'),
(337, 'Faire une croisade'),
(338, 'Une bonne ratonnade'),
(339, 'Un tanga ayant appartenu à Napoléon'),
(340, 'Une fosse commune en Érythrée'),
(341, 'Le jour du Seigneur'),
(342, 'Un charnier plein de malgaches'),
(343, 'John Locke'),
(344, 'Les noms de famille des Malgaches'),
(345, 'Les Allemands'),
(346, 'Les Italiens'),
(347, 'Les Turcs'),
(348, 'Les Américains'),
(349, 'Les Français'),
(350, 'Les Françaises'),
(351, 'François Berléand'),
(352, 'Un moule-bite trop serré pour devenir stérile'),
(353, 'Tchernobyl'),
(354, 'Un filet de poulet périmé depuis trois semaines'),
(355, 'Une histoire de Père Castor'),
(356, 'Eric & Ramzy'),
(357, 'La Shoah'),
(358, 'Le Ku Klux Klan'),
(359, 'S’autosucer'),
(360, 'La disparition d’Estelle Mouzin'),
(361, 'Tuer des Portugais'),
(362, 'Un pogrom de gens du voyage'),
(363, 'Les Portugais'),
(364, 'L’illettrisme'),
(365, 'Prendre l\'option "Latin" au collège'),
(366, 'Les Insoumis'),
(367, 'Un oubli de pilule'),
(368, 'La soupe au dentier de Mémé Jacqueline'),
(369, 'Un kyste anal'),
(370, 'Lapider sa femme'),
(371, 'Des auréoles sous les bras'),
(372, 'Des préservatifs "goût roquefort"'),
(373, 'Des élèves en SEGPA'),
(374, 'Une verrue mal placée'),
(375, 'Adam et cette salope d’Eve'),
(376, 'Nicolas Cage'),
(377, 'Les couilles de Caitlyn Jenner'),
(378, 'Une petite fille en fauteuil roulant'),
(379, 'Un petit fauteuil en fille roulante'),
(380, 'Un manchot qui essaye d’applaudir'),
(381, 'Être gay'),
(382, 'Dulculoax'),
(383, 'La bite à Dudule'),
(384, 'Une plage naturiste'),
(385, 'Un sex shop'),
(386, 'Auschwitz'),
(387, 'Une gorge un peu trop profonde'),
(388, 'Le Raptor dissident'),
(389, 'Une conjonctivite virale'),
(390, 'Les albinos'),
(391, 'L’Islam des Tyrans'),
(392, 'Les jeunes'),
(393, 'Les vieux avec des couches'),
(394, 'Le Forum International de Davos'),
(395, 'Le Code de Procédure Pénale'),
(396, 'La Grande Allemagne'),
(397, 'Une boîte de Monopoly'),
(398, 'L’Allemagne Nazie'),
(399, 'La France de Vichy'),
(400, 'Bowser'),
(401, 'Le chiffre « 7 »'),
(402, 'Stelios Kontos'),
(403, 'Julien Lepers'),
(404, 'Baiser la princesse Zelda'),
(405, 'Un Pikachu level 95 dans la Forêt de Jade'),
(406, 'Le juge des Tutelles'),
(407, 'Baiser au rayon "charcuterie"'),
(408, 'Avoir le teint basané'),
(409, 'Le gouvernement "Raffarin 2"'),
(410, 'L’Ouragan « Bernard »'),
(411, 'La loi sur le Renseignement'),
(412, 'Ne pas croire en l’existence des Langoustines'),
(413, 'L\'homme qui suçait des sèche-linge.'),
(414, 'Une invitation pour le one-man-show de Sylvain Mirouf'),
(415, 'Le trident de Poséidon'),
(416, 'Dessiner des portraits d’animateurs d’M6 avec son pipi dans la neige'),
(417, 'Photocopier du sable'),
(418, 'Devenir imitateur de machine à café'),
(419, 'Jean-François Colissimo'),
(420, 'Réanimer un plat de couscous'),
(421, 'Xavier Dupont de Ligonnès'),
(422, 'Une formation de testeur de chemise chez Kiabi'),
(423, 'Louer Laurence Boccolini pour son anniversaire'),
(424, 'Papy Brossard'),
(425, 'Dwayne Johnson'),
(426, 'Le combo bière/tuning/inceste'),
(427, 'France 3 Picardie'),
(428, 'Une traînée d’urine sur le lino du salon'),
(429, 'Farcir un scout'),
(430, 'Parfumer un carrefour giratoire'),
(431, 'Faire cuire Christophe Dechavanne'),
(432, 'Collectionner les ampoules de vestibules'),
(433, 'Faire du vélo sur du jonc de mer avec Michel Drucker'),
(434, 'Une statue de John Cena en pignons de pin.'),
(435, 'Un nu frontal de Passe-Partout en IMAX'),
(436, 'Payer ses impôts en France'),
(437, 'Une soirée barbecue à Charleville-Mézières'),
(438, 'En Pâtisserie, pour réussir la cuisson de ______. Il est indispensable de bien ______.'),
(439, 'Suivre la voie de l’Illumination'),
(440, 'Se déguiser en Shrek pour faire l’amour'),
(441, 'Jean Michel Voidechiotte'),
(442, 'Voler des Hobbits sur le tournage du Seigneur des Anneaux'),
(443, 'La levrette avec un semi-remorque'),
(444, 'Traire un bougnoul'),
(445, 'Décapiter des aides-soignantes'),
(446, 'Manger un radiateur'),
(447, 'La tirelire secrète des juifs plein de thunes'),
(448, 'David Centrifugeuse'),
(449, 'Oublier de déclarer la naissance de son enfant à la Mairie'),
(450, 'Les députés de "La République en Marche"'),
(451, 'Une partouze de Sénateurs « Les Républicains »'),
(452, 'Un "69" avec Benito Mussolini'),
(453, 'Édouard Philippe'),
(454, 'La bite'),
(455, 'Zoner au bar PMU'),
(456, 'Perdre les eaux dans le Sahara'),
(457, 'Un musulman honnête'),
(458, 'La taille moyenne des pénis Chinois'),
(459, 'Un Canadien, une pute et un homosexuel'),
(460, 'Pol Pot le despote'),
(461, 'La communauté des joueurs de League of Legends'),
(462, 'Le traitement des minorités sexuelles dans la saga « Harry Potter »'),
(463, 'Le jeu du FN'),
(464, 'Refiler le SIDA à un trisomique'),
(465, 'Avoir le syndrome Gilles de la Tourette quand on est muet'),
(466, 'La petite Maëlys'),
(467, 'Présenter le JT sur Équidia'),
(468, 'L’agence de la NSA de Rambouillet'),
(469, 'Le trafic d’organes'),
(470, 'Les zadistes'),
(471, 'Une diarrhée générale'),
(472, 'Tomber amoureux d’une courroie de transmission'),
(473, 'Le tueur du bowling de la Chapelle sur Erdre'),
(474, 'Le Kosovo'),
(475, 'Un chauffeur de bus sans bras et sans jambes'),
(476, 'Prétexter une fuite d’eau pour mater la raie du plombier'),
(477, 'Se faire inséminer par Jean Yves Lafesse'),
(478, 'Se faire remplir par « Taureau Ailé »'),
(479, 'Dénoncer un juif'),
(480, 'Le fétichisme des prothèses de jambes'),
(481, 'Racheter un club de foot en Bosnie'),
(482, 'Une simulation d’hôtesse de caisse'),
(483, 'L’ensemanceur d’antilopes'),
(484, 'Le patriarcat'),
(485, 'La vulnérabilité des femmes'),
(486, 'Remettre en question l’ordre social'),
(487, 'Un Speedtest en Corrèze'),
(488, 'Faire boire de l’essence à un cheval pour qu’il avance plus vite'),
(489, 'Donner le SIDA à une sage-femme'),
(490, 'Soigner la polio avec des gousses de vanille'),
(491, 'Devenir propriétaire à Brou sur Chantereine'),
(492, 'Un Octorok'),
(493, 'Un fight de supporters de Châteauroux sur une aire d’autoroute'),
(494, 'Un génocide de Chenipans dans la Forêt de Jade'),
(495, 'Combattre pour la suprématie de la race blanche'),
(496, '10 points pour Gryffondor'),
(497, 'Le rétablissement de l\'ordre républicain'),
(498, 'Rechercher un déporté sur Tinder'),
(499, 'Déporter des fabricants de radiateurs'),
(500, 'Du nettoyeur vitre Rainett'),
(501, 'Ouvrir un Snap de Jawad'),
(502, 'Les restes du chibre de Louis XVI'),
(503, 'Ressusciter Mouammar Kadhafi'),
(504, 'Le chevalier de la Vierge'),
(505, '100 kilos de pertes blanches'),
(506, 'Martin Fourcade'),
(507, 'Chantal Goya'),
(508, 'La redif’ du viol de sa petite sœur sur M6 Replay'),
(509, 'Thierry Lhermitte'),
(510, 'Thierry Beccaro'),
(511, 'Jean-Pierre Coffe'),
(512, 'Écouter sa mère baiser sur Spotify'),
(513, 'L\'Eure-et-Loir'),
(514, 'Beauvais'),
(515, 'S\'ambiancer avec des grands brûlés'),
(516, 'Drifter sur le parking d\'un Simply Market'),
(517, 'Le rap conscient'),
(518, 'Ectoplasma'),
(519, 'Dompter des portes de placard'),
(520, 'Les cheminots'),
(521, 'Un filet de sandre'),
(522, 'Les Sénégalais'),
(523, 'Les Jeux Paralympiques'),
(524, 'Le temps de cuisson des Juifs '),
(525, 'Godzilla en vacances à Saint Trop’ '),
(526, 'S\'acheter une Dacia'),
(527, 'Adhérer à "Debout La France"'),
(528, 'Un burrito au foutre'),
(529, 'Christophe Castaner'),
(530, 'Les seins de Jane Birkin'),
(531, 'Faire une brillante carrière d’aide-soignant'),
(532, 'Souder ses couilles contre une locomotive de TER'),
(533, 'Ne pas savoir dire "non" à son banquier'),
(534, 'Dire aux pauvres qu’ils n’ont qu’à travailler plus'),
(535, 'Israël'),
(536, 'Le pénis de Patrick Bruel'),
(537, 'Prendre sa douche avec Claude Makélélé'),
(538, 'Les téléspectateurs de TPMP'),
(539, 'Moundir de Koh-Lanta'),
(540, 'Discriminer un handicapé'),
(541, 'Avoir le courage de dire la vérité aux homosexuels'),
(542, 'Hurler sur un enfant sourd'),
(543, 'LesFurets.com'),
(544, 'Un tatouage avec le prénom de sa mère'),
(545, 'Un chef d’entreprise qui roule en Renault Fuego'),
(546, 'Un gilet jaune bedonnant sur un rond-point'),
(547, 'Des éjaculations involontaires devant le JT d’Arte'),
(548, 'Un concert privé de La Fouine'),
(549, 'Les femmes à trois tétons'),
(550, 'Être gay mais ne pas aimer les enfants'),
(551, 'Le livret A de François Fillon'),
(552, 'Le légendaire fils caché de Laurent Ruquier'),
(553, 'La soeur de Forrto');
