INSERT INTO `Answers` (`id`, `text`, `definition`) VALUES
(1, 'Ma bite', ''),
(2, 'Coller la Petite', 'Rapport sexuel non désiré avec un Camerounais en boîte de nuit'),
(3, 'Les Chinois', ''),
(4, 'Les Noirs', ''),
(5, 'Soixante-douze vierges', 'Femmes non déflorées promises en récompense aux bons musulmans (une traduction alternative plus récente du Coran affirme qu’il s’agirait plutôt de raisins blancs, vachement moins sympa du coup...).'),
(6, 'Un Juif, un unijambiste et un Belge', ''),
(7, 'Les Juifs', 'Peuple martyr.'),
(8, 'Joseph Goebbels', 'Ministre de la Propagande du IIIème Reich au physique particulièrement ingrat'),
(9, 'Me follow-back quand je l’ai follow', ''),
(10, 'Des nudes de Michel Cymès', 'Médecin et journaliste Français assez lubrique.'),
(11, 'La chatte à ta mère', ''),
(12, 'Me sucer', ''),
(13, 'La probité des Balkany', 'Couple de politiciens Français condamnés par la Justice à de nombreuses reprises.'),
(14, 'Regarder un bon porno', ''),
(15, 'Un bras d’enfant', ''),
(16, 'Un enfant Rohingya', 'Minorité ethnique Birmane persécutée, notamment, du fait de sa religion (musulmane)'),
(17, 'Logan Paul', 'Youtuber Américain qui a notamment créé une controverse après avoir filmé un cadavre.'),
(18, 'Le glyphosate', 'Herbicide controversé.'),
(19, 'Un charter rempli de Moldaves', ''),
(20, 'Un seigneur noir des Siths', 'Antagonistes des Jedis dans l’univers de « Star Wars ».'),
(21, 'Ma bite et mon couteau', ''),
(22, 'Déféquer dans un melon', ''),
(23, 'Prendre un enfant par la main', ''),
(24, 'Filmer un cadavre pour faire le buzz', 'Fait d’armes de Logan Paul, Youtuber Américain'),
(25, 'La zoophilie', 'La passion des animaux.'),
(26, 'De l’eau de Javel', 'Le meilleur moyen de nettoyer une scène de crime.'),
(27, 'Un petit mojito sur les quais', 'L’After-work préféré de Gaspard et Benjamin.'),
(28, 'Du quinoa', ''),
(29, 'Une pipe vite fait entre deux avions', ''),
(30, 'Les Restos du Cœur', ''),
(31, 'Un cubi de Villageoise', 'Vin rouge Français médiocre et très bon marché prisé des bénéficiaires du RSA'),
(32, 'Du surimi', 'Spécialité culinaire bas de gamme à base de chair de poissons'),
(33, 'Regarder ses voisins avec des jumelles', ''),
(34, 'Sentir ma main après s’être gratté la raie', ''),
(35, 'La nation Française', ''),
(36, 'L’affaire Fillon : la comédie musicale', ''),
(37, 'Sucer un pote pour lui rendre service', ''),
(38, 'Les soi-disant victimes d’Harvey Weinstein', 'Producteur Américain prétendument accusé de viols'),
(39, 'Avoir une érection pendant un entretien d’embauche', ''),
(40, 'La gaule matinale', ''),
(41, 'Une coupe menstruelle pleine', 'Concurrent du tampon pour ces dames. Peut également servir de récipient pour la crème anglaise avec un fondant au chocolat.'),
(42, 'La société de consommation', ''),
(43, 'Goûter son sperme juste pour voir', 'Tout le monde l’a déjà fait, non ? Non, vraiment ?'),
(44, 'Le dernier porno de Dorothée', ''),
(45, 'Guy Georges', 'Tueur en série Français, assez violent.'),
(46, 'Eva Mendès', 'Pulpeuse actrice Américaine d’origine Cubaine, compagne de Ryan Gosling'),
(47, 'La neutralité du Web', ''),
(48, 'La diarrhée post-concert de jazz manouche', ''),
(49, 'Du Smecta', 'Médicament pour soigner la diarrhée qui a le goût et l’aspect du plâtre '),
(50, 'Une petite virée improvisée à Deauville', '');