INSERT INTO `Questions` (`id`, `text`) VALUES
(1, 'Grâce aux vidéos de Tibo InShape j’ai enfin pu ______.'),
(2, 'L’autre jour ma grand-mère m’a proposé ______, un véritable enchantement pour moi.'),
(3, 'À mon grand regret, les nazis n’ont pas pu ______.'),
(4, '______ et ______ n’ont pas vraiment de mérite je trouve.'),
(5, 'Tu as déjà ______ pour faire plaisir à ta mère ?'),
(6, 'L’autre jour j’ai donné ______ au Téléthon. Ça devrait leur être utile.'),
(7, 'Je ne supporte plus ______ depuis qu’ils ont changé leur politique tarifaire.'),
(8, 'Papa ? Quand est-ce qu’on achète ______ ? Maman me l’avait promis !'),
(9, 'Ma Banque m’a appelé Mardi. Ma conseillère a décidé de ______. Je suis ravi.'),
(10, 'Allons enfants de la Patrie, ______ est arrivé.'),
(11, 'Tu connais Benjamin ? L’autre jour il m’a proposé de ______. Il est vraiment dégueulasse.'),
(12, 'L’Espagne c’est vraiment le pays idéal pour ______.'),
(13, 'J’étais sur une île déserte l’été dernier. J’ai été très surpris de découvrir que même ______ et ______ peuvent survivre là-bas.'),
(14, 'Le Front National a décidé ______. Un grand jour pour la France.'),
(15, 'Pour ______ avec toi, je ferai n\'importe quoi.'),
(16, '______, ______ et ______ : les ingrédients essentiels d’une bonne soirée.'),
(17, 'Je me suis toujours demandé pourquoi ______ n’a jamais voulu ______. C’était pourtant évident.'),
(18, '______ : rien de mieux pour désinfecter les plaies !'),
(19, '______ : la meilleure façon d’attirer les hommes virils.'),
(20, 'Quelle surprise ! Le Parlement Européen était en fait ______ !'),
(21, 'Pour lutter efficacement contre l’herpès génitale, il y a ______.'),
(22, 'Les Youtubeurs tchétchènes sont vraiment de plus en plus créatifs, dernièrement ils ont décidé de ______.'),
(23, 'Les hommes d\'âge mûr sont réputés pour ______.'),
(24, 'Pour mon tiramisu, j’ai un ingrédient secret : ______. C’est toujours un succès.'),
(25, 'Les pubs Banania ne sont pas tellement racistes au fond. Qui n\'a pas ______ avec un noir ?'),
(26, 'Pour Chevalier Jedi devenir, ______ tu devras !'),
(27, '"House of Cards" c’est vraiment trop surfait. Maintenant, je regarde "______" sur Netflix.'),
(28, '______ et ______ m’ont convaincu de me convertir à l\'Islam.'),
(29, 'Une fellation après la sodomie, il vaut mieux en parler avant. En revanche pour ______, pas la peine.'),
(30, 'Depuis quand tu n’as pas ______ ? Ben, tu sais, en ce moment j’évite depuis que j\'ai eu affaire à ______...'),
(31, 'Enfin les vacances scolaires ! Papa va enfin pouvoir ______. Depuis le temps qu’on attendait ça…'),
(32, 'Sortir en boîte avec ______ ? Tu n’y pense pas ! Je tiens trop à ______.'),
(33, 'Je parle de mieux en mieux Anglais : maintenant je sais dire « ______ » sans que les gens ne comprennent « ______ ».'),
(34, '______ est un fléau pour ______. Emmanuel Macron doit agir vite !'),
(35, 'Je n’ai toujours pas bien compris la fin du dernier Star Wars... ______ a bien tué ______, non ?'),
(36, 'Pour monter un meuble IKEA, il vous faut : ______, ______ et un peu d’huile de coude.'),
(37, '« Crédit Agricole : ______ pour vous ! »'),
(38, '______ ont empêché ______ de conquérir ______ : les mystères de l\'Histoire...'),
(39, '______ ou ______ : il faut choisir !'),
(40, '______ sont vraiment des voleurs. Ce n’est pas un cliché.'),
(41, 'À quand une nouvelle saison de « ______ » ? Je n\'en peux plus d\'attendre !'),
(42, 'Mon patron veut que je puisse ______ avant la réunion de mardi. Je n’y arriverai jamais à temps...'),
(43, 'Nom de Dieu de bordel de merde : je n’aurai pas le temps de ______ avant ______ !'),
(44, '______ et ______ sont partis en Syrie. On n’est pas prêts de les revoir !'),
(45, '______ est vraiment sexy ! Je ne peux pas me contenir en sa présence.'),
(46, 'La Suède est un pays qui me fait rêver. Là-bas, pas de chômage ni de terrorisme. Tout ça grâce à ______.'),
(47, 'Sur Canal Plus, j’ai récemment découvert ______. Un programme de qualité !'),
(48, 'Cette nuit sur Arte, il y avait ______ et ______ dans une pièce de théâtre incroyable.'),
(49, 'L’art moderne ? Je ne comprends toujours pas. Surtout quand ______ et ______ réalisent des « performances scéniques improbables ».'),
(50, 'Tu crois que ______ est gay ? Non, impossible il sort avec ______ !'),
(51, 'La dernière excuse de ______ pour ne pas m\'inviter à diner est vraiment pitoyable !'),
(52, 'Maïté est à la cuisine ce que ______ est à ______.'),
(53, 'Pour le service commercial, tapez 1. Pour ______, tapez ______. Sinon, merci de patienter.'),
(54, 'Sainte ______ va bientôt être canonisée. J’ai hâte.'),
(55, 'Saint ______ va bientôt être canonisé. J’ai hâte.'),
(56, 'Il y a quelques jours, un collègue m’a présenté à ______. Je ne pensais pas que le courant passerait aussi bien.'),
(57, 'Mettre fin à ______ : l’objectif principal pour la COP 24.'),
(58, '« Les nouvelles aventures de ______ » : le nouveau grand succès des Studios Disney.'),
(59, 'Au dernier G20, les négociations ont tourné autour de ______. Pas un mot sur ______. Bravo !'),
(60, 'Tu te souviens de ______ ? Moi j\'avais trop bu, aucun souvenir...'),
(61, 'Ce soir j’ai ______ qui vient chez moi pour réviser. Moi, j’ai plutôt envie de ______.'),
(62, 'Ma maman m’a déjà surpris en train de ______. C’était très gênant.'),
(63, '______ : un sujet de discorde dans ma famille.'),
(64, 'Il était une fois ______. Puis, ils se marièrent et eurent ______.'),
(65, 'One, two, three : viva ______ !'),
(66, 'J’ai failli tomber sur ______ en fouillant dans les affaires de ______.'),
(67, '______ et ______ sont vraiment les pires ennemis de la démocratie.'),
(68, 'Tu ne devineras jamais qui j’ai croisé au meeting de ______ : ______ !'),
(69, 'Ma plus grande phobie ? ______.'),
(70, 'Ils ont enfin trouvé le titre de la biographie de Julien Lepers : ______'),
(71, 'Le dernier film de ______ ne m’a pas plu. Il y a trop de _____.'),
(72, 'Ils n’ont vraiment plus d’imagination pour les noms des Pokémons ! Pikachu, Carapuce, passe encore, mais ______, là ça dépasse les bornes.'),
(73, '______, passe encore, mais ______ à ton âge, c\'est de la folie !'),
(74, 'Liberté, Égalité, ______.'),
(75, 'Hey Vanessa ! Quand est-ce qu’on voit ______ ?'),
(76, 'J’en ai marre de ______, ce n’est pas lamentable d\'en arriver là !'),
(77, 'La dernière fois que j’ai pensé à ______, je n’ai pas pu contenir ______.'),
(78, '______ ? Il ne fallait vraiment pas y aller, moi je te le dis.'),
(79, 'J’ai dû hypothéquer ______ pour acheter ______.'),
(80, 'Au fond, ______, c’était pas si grave.'),
(81, 'On ne pourra pas aller sur Mars à cause de ______. Quel dommage…'),
(82, 'Les habitants Guéret sont abasourdis : les corps de ______ et ______ ont été retrouvés avec ______ dans la gorge.'),
(83, '______ n’est pas la meilleure façon d’attirer les femmes riches.'),
(84, 'On m’a diagnostiqué ______. Mais je garde espoir.'),
(85, 'La principale cause de décès chez les francs-maçons est ______.'),
(86, 'Avant de ______, commence déjà par ______.'),
(87, 'Teddy ? Passe-moi ______, s’il te plait, tu seras gentil.'),
(88, 'En cette période de grand froid, EDF a décidé de ____.'),
(89, 'Star Wars Episode IX : ______.'),
(90, '______ : mon attente. ______ la réalité.'),
(91, '2015, c’était vraiment ______.'),
(92, 'Je suis né en 1990, l’année où mes parents ont choisi de ______.'),
(93, 'Pour me concevoir, mes parents ont préféré ______.'),
(94, 'Aujourd’hui, pour ne pas être traité d’homophobe, il faudrait presque ______ !'),
(95, 'La sextape de ______ et ______ m’a particulièrement émoustillé.'),
(96, 'L’autre jour, ______ a sonné à ma porte.'),
(97, 'J’ai prêté ______ à ______. Depuis, impossible de remettre la main dessus.'),
(98, 'J’ai prêté ______ à ______. Depuis, impossible de remettre la main dessus...'),
(99, 'Pour ta dépression, tu as pensé à ______ ?'),
(100, 'Zouuuulou, c’est la danse ______.'),
(101, 'Regarde Maman : ______.'),
(102, '______, c’est mieux à Tourcoing qu’à Saint Tropez.'),
(103, '"Martine et ______" : le meilleur tome de la série.'),
(104, 'Quand j’ai appris que ma grand-mère avait ______, je ne l\'ai plus regardé de la même façon.'),
(105, 'Dans le Coran, la soixante-neuvième sourate nous apprend comment ______.'),
(106, 'Au nom d’Allah, le tout miséricordieux, le très miséricordieux : j’ai enfin pu ______.'),
(107, 'Acheter ______, c’est la meilleure affaire que j’ai pu faire depuis bien longtemps.'),
(108, '______ et ______ sont des rituels très importants à respecter en Inde.'),
(109, 'L’homme qui couche avec ______ est une abomination.'),
(110, 'Je vais ______ jusqu’à ce que mort s’en suive.'),
(111, 'Le dernier album de ______ est très réussi.'),
(112, '______ a déclaré : "J’aime ______."'),
(113, 'Les nazis n’ont pas été jusqu’au bout, il fallait aussi exterminer ______.'),
(114, 'Le foot c’est bien, mais ______ avec ______ c’est mieux.'),
(115, 'Après ______, je suis devenu stérile.'),
(116, 'Pour obtenir mon stage j’ai dû ______, mais c’était nécessaire.'),
(117, 'Grâce à ______, je serai à l’abri du besoin pendant très longtemps.'),
(118, '______ est assurément le meilleur moyen de lutter efficacement contre ______.'),
(119, 'Si Juvabien, c’est ______.'),
(120, 'On a trouvé le nouveau présentateur de Koh Lanta : ce sera ______. Un choix audacieux.'),
(121, '_____ a déclaré : "______ ? Je la soulèverai bien."'),
(122, 'Le nouveau slogan des Insoumis : "______."'),
(123, 'On a remplacé le bouton nucléaire de Donald Trump par ______. Un choix judicieux.'),
(124, 'PRANK : IL SURPREND ______ AVEC ______ : ÇA TOURNE MAL.'),
(125, 'Pour lutter contre le chômage des cadres, il faudrait qu’Emmanuel Macron pense à ______.'),
(126, 'Pendant l’hiver dans le grand Nord Canadien, on peut souvent observer ______ en train de ______.'),
(127, 'C’est un avion ? Non, c’est un oiseau ! Non, c’est ______.'),
(128, 'Pour faire disparaître les tâches il y a ______.'),
(129, 'Carglass répare, Carglass ______.'),
(130, 'Tout comme « La petite souris », ______ n’est qu’un mythe.'),
(131, 'Fais-moi l’amour avec ______, parce qu’avec ______ ça rentre pas.'),
(132, 'Un grand pouvoir implique ______.'),
(133, 'Pour les fêtes, j’ai emmené ______ au Marché de Noël.'),
(134, 'Un grand artiste saura ______ mieux que personne.'),
(135, '______ : encore un complot du gouvernement.'),
(136, '______ : du travail bâclé.'),
(137, 'On se rappelait tous de ce qu’on faisait quand on a appris pour ______ : moi j’étais avec ______.'),
(138, 'L’autre jour, ton frère m’a donné un conseil : ______. Mais je n’aurai pas dû l’écouter.'),
(139, 'Pouvez-vous ______ ? Cordialement, la Direction.'),
(140, 'Certains milliardaires sont prêts à payer des milliers d\'euros pour ______.'),
(141, 'Je veux ______, ici et maintenant !'),
(142, 'Bonjour. Je suis bien chez ______ ?'),
(143, 'L\'autre jour, j\'ai croisé ______ au magasin de bricolage.'),
(144, '______ est sans doute le meilleur moyen de faire des rencontres sérieuses.'),
(145, 'Le nouveau groupe de black métal suédois à la mode : ______. Un régal.'),
(146, 'Ils ont finalement choisi ______ comme nouveau chroniqueur dans TPMP.'),
(147, 'Devenir Vegan, c\'est un peu comme ______.'),
(148, 'Le dernier reportage de TF1 sur ______ m\'a coupé l\'appétit.'),
(149, 'Avant de mourir, ma dernière volonté sera sans doute ______.'),
(150, 'Ils ont tout tenté pour obtenir ______ au Proche-Orient, même ______.'),
(151, 'L’année prochaine, je rentre à l’Université pour ______. J’y croiserai peut-être ______.'),
(152, 'Depuis qu’il est sorti de prison, je ne reconnais plus ______.'),
(153, 'Après six mois d’attente, je vais enfin pouvoir ______. C’est ______ qui sera content(e) !'),
(154, 'Cette année, pour l’Eurovision, ______ va représenter la France.'),
(155, 'Réuni en séance plénière au Palais du Luxembourg, le Sénat va enfin discuter la légalité de ______.'),
(156, 'Le Premier Ministre me fait vraiment penser à ______.'),
(157, 'En tant que réalisateur, j’ai longtemps hésité entre un biopic sur ______ et sur ______.'),
(158, 'Deux inconnus, deux anonymes, mais pourtant. Pulvérisés, sur l’autel, de ______.'),
(159, 'Au nord, c\'étaient les corons, la terre c\'était ______.'),
(160, 'Je, je suis libertine. Je suis ______. Je, je suis si fragile. Qu\'on me tienne ______.'),
(161, 'Toutes ces choses qui avaient un prix, qui font l\'envie de vivre et le désir, et le plaisir aussi, qu\'on me donne ______ !'),
(162, 'On vous souhaite tout le bonheur du monde, Et que quelqu\'un vous tende ______.'),
(163, 'Cette année-là, le rock\'n\'roll venait d\'ouvrir ses ailes. Et dans mon coin je chantais « ______ », Et le public aimait ça.'),
(164, '______ ou ______, il faut choisir.'),
(165, '______ : le meilleur Youtubeur gaming.'),
(166, 'Avec mes difficultés financières, mon conseiller financier m’a orienté vers ______. Depuis, je refais surface.'),
(167, 'Quand il a refusé mon prêt immobilier, mon banquier m’a dit d’aller ______.'),
(168, '2019, année de ______.'),
(169, '______ : c’est « so 2012 ».'),
(170, 'Avant, j’allais sur MSN pour ______.'),
(171, 'Prendre sa douche avec ______, une expérience inoubliable.'),
(172, 'Lundi dernier, j’ai croisé ______ chez le barbier.'),
(173, 'Ma femme de ménage s’appelle ______.'),
(174, '______ : la pire maladie qu’on puisse avoir.'),
(175, 'J’ai failli revendre ma PS4 pour m’acheter ______. J’aurais tellement pu faire une bonne affaire…'),
(176, 'Qui se souvient de ______ ? C’était vraiment « has been ».'),
(177, 'À côté de la crèche de mon quartier, ils ont découvert ______.'),
(178, 'En Égypte, dans la Vallée des Rois, ils ont enfin découvert ______.'),
(179, 'Le Féminisme à la Française c’est ______.'),
(180, 'Pour séduire une femme en trois minutes, rien de tel que ______.'),
(181, '« ______ » : une création originale Canal +.'),
(182, 'Génial, découvre maintenant ______ dans ton Happy Meal !'),
(183, 'Impossible de trouver ______ dans son supermarché en 2018.'),
(184, 'Pour solutionner la crise des migrants, les bénévoles ont demandé à ______ d’agir.'),
(185, '______ ou ______ : des solutions viables pour réduire les inégalités sociales en France.'),
(186, 'Pour ______, évite de manger trop gras et trop salé !');
